timezone: Europe/Berlin
highlighter: pygments
markdown: redcarpet
permalink: /post/:title
relative_permalinks: true

redcarpet:
  extensions: [autolink]

exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]

paginate: 5
paginate_path: '/blog/:num'

excerpt_separator: "\n\n\n"

# own settings
name: alpoza.github.io
domain: alpoza.github.io
url: http://alpoza.github.io/minddust.github.io/
description: Portfolio website of Stephan Groß
copyright: 2013&mdash;2015
author:
    name: Stephan Groß
    github_link: https://github.com/alpoza
    twitter_link: https://twitter.com/alpoza
